export async function onRequest(context) {
    // 从 Cloudflare 环境中读取变量
    const config = {
        SUPABASE_URL: context.env.SUPABASE_URL,
        SUPABASE_ANON_KEY: context.env.SUPABASE_ANON_KEY
    };

    return new Response(JSON.stringify(config), {
        headers: {
            "Content-Type": "application/json;charset=UTF-8",
        },
    });
}





-- 1. 创建用户表
CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    emp_id TEXT UNIQUE NOT NULL,
    name TEXT NOT NULL,
    role TEXT DEFAULT 'user' -- admin (管理员) 或 user (普通员工)
);

-- 2. 创建题库表
CREATE TABLE questions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source TEXT NOT NULL,
    type TEXT NOT NULL,
    question TEXT NOT NULL,
    options JSONB DEFAULT '[]'::jsonb,
    answer TEXT NOT NULL
);

-- 3. 创建试卷表
CREATE TABLE exams (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,
    question_ids JSONB NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 4. 写入初始用户（你可以根据需要在此修改或新增工号）
INSERT INTO users (emp_id, name, role) VALUES
('1001', '系统管理员', 'admin'),
('0038193', '任滨海', 'user'),
('0037829', '李杰', 'user'),
('0021903', '何君文', 'user'),
('0037787', '张瑞明', 'user'),
('0031292', '莫守烨', 'user'),
('0015095', '包文魁', 'user'),
('0038227', '周志瑜', 'user'),
('0037788', '程世贸', 'user');

anon:
eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlwZmZ0bm12eXpzcmNldnpybGJxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3OTAwNzk0MDAsImV4cCI6MjEwNTY1NTQwMH0.JlEN6xAbsCJxUYskkk6UgaRFagt0OU-ldSgmlR1_V7U

url:
https://ypfftnmvyzsrcevzrlbq.supabase.co